lab_7/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name = 'lab_7'
urlpatterns = [
# Домашняя страница
    path(r'', views.index, name='index'),
    path(r'^topics/$', views.topics, name='topics'),
    path(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    path(r'^new_topic/$', views.new_topic, name='new_topic'),
    path(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    path(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),

]

laba_django/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'^users/', include('users.urls', namespace='users')),
    path(r'', include('lab_7.urls',namespace='lab_7')),
]

users/urls.py
from django.contrib.auth import authenticate, login
from . import views
from django.contrib.auth import views as auth_views
from django.urls import path,include
from . import views
app_name = 'users'
urlpatterns = [
# Страница входа
path(r'^login/$', auth_views.LoginView.as_view(template_name= 'users/login.html'),name='login'),
path(r'^logout/$', views.logout_view, name='logout'),
    path(r'^register/$', views.register, name='register'),
]

lab_7/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Topic(models.Model):
#"""Тема, которую изучает пользователь"""
     text = models.CharField(max_length=200)
     date_added = models.DateTimeField(auto_now_add=True)
     owner = models.ForeignKey(User,on_delete=models.CASCADE)
     def __str__(self):
#"""Возвращает строковое представление модели."""
        return self.text

class Entry(models.Model):
#"""Информация, изученная пользователем по теме"""
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    def __str__(self):
#"""Возвращает строковое представление модели."""
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

lab_7/forms.py
from django import forms
from .models import Topic, Entry
class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
# Create your views here.
def index(request):
#"""Домашняя страница приложения Learning Log"""
    return render(request, 'lab_7/index.html')
@login_required
def topics(request):
#"""Выводит список тем."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'lab_7/topics.html', context)
@login_required
def topic(request, topic_id):
#"""Выводит одну тему и все ее записи."""
    topic = Topic.objects.get(id=topic_id)
# Проверка того, что тема принадлежит текущему пользователю.
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'lab_7/topic.html', context)
@login_required
def new_topic(request):
#"""Определяет новую тему."""
    if request.method != 'POST':
# Данные не отправлялись; создается пустая форма.
        form = TopicForm()
    else:
# Отправлены данные POST; обработать данные.
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
        return HttpResponseRedirect(reverse('lab_7:topics'))
    context = {'form': form}
    return render(request, 'lab_7/new_topic.html', context)
@login_required
def new_entry(request, topic_id):
#"""Добавляет новую запись по конкретной теме."""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
# Данные не отправлялись; создается пустая форма.
        form = EntryForm()
    else:
# Отправлены данные POST; обработать данные.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('lab_7:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'lab_7/new_entry.html', context)
@login_required
def edit_entry(request, entry_id):
#"""Редактирует существующую запись."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
# Исходный запрос; форма заполняется данными текущей записи.
        form = EntryForm(instance=entry)
    else:
# Отправка данных POST; обработать данные.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('lab_7:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'lab_7/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.urls import reverse

def logout_view(request):
#"""Завершает сеанс работы с приложением."""
    logout(request)
    return HttpResponseRedirect(reverse('lab_7:index'))
def register(request):
#"""Регистрирует нового пользователя."""
    if request.method != 'POST':
# Display blank registration form.
        form = UserCreationForm()
    else:
# Обработка заполненной формы.
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
# Выполнение входа и перенаправление на домашнюю страницу.
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('lab_7:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

templates/lab_7/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Lab_7</title>
{% bootstrap_css %}
{% bootstrap_javascript %}
</head>

<body>
<!-- Статическая навигационная панель -->
<nav class="navbar navbar-default navbar-static-top">
<div class="container">
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed"
data-toggle="collapse" data-target="#navbar"
aria-expanded="false" aria-controls="navbar">
</button>
 <a class="navbar-brand" href="{% url 'lab_7:index' %}">
Lab_7</a>
</div>
<div id="navbar" class="navbar-collapse collapse">
<ul class="nav navbar-nav">
<li><a href="{% url 'lab_7:topics' %}">Topics</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
{% if user.is_authenticated %}
<li><a>Hello, {{ user.username }}.</a></li>
<li><a href="{% url 'users:logout' %}">log out</a></li>
{% else %}
<li><a href="{% url 'users:register' %}">register</a></li>
<li><a href="{% url 'users:login' %}">log in</a></li>
{% endif %}
</ul>
</div><!--/.nav-collapse -->
</div>
</nav>

<div class="container">
<div class="page-header">
{% block header %}{% endblock header %}
</div>
<div>
{% block content %}{% endblock content %}
</div>
</div> <!-- /container -->

</body>
</html>

templates/lab_7/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "lab_7/base.html" %}
{% block content %}
<p><a href="{% url 'lab_7:topic' topic.id %}">{{ topic }}</a></p>
<p>Edit entry:</p>
<form action="{% url 'lab_7:edit_entry' entry.id %}" method='post'>
{% csrf_token %}
{{ form.as_p }}
<button name="submit">save changes</button>
</form>
{% endblock content %}
</body>
</html>

templates/lab_7/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "lab_7/base.html" %}
{% block header %}
<div class='jumbotron'>
<h1>Track your learning.</h1>
</div>
{% endblock header %}
{% block content %}
   <h2>
<a href="{% url 'users:register' %}">Register an account</a> to make
your own Learning Log, and list the topics you're learning about.
</h2>
<h2>
Whenever you learn something new about a topic, make an entry
summarizing what you've learned.
</h2>
{% endblock content %}
</body>
</html>

templates/lab_7/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "lab_7/base.html" %}
{% block content %}
<p><a href="{% url 'lab_7:topic' topic.id %}">{{ topic }}</a></p>
<p>Add a new entry:</p>
<form action="{% url 'lab_7:new_entry' topic.id %}" method='post'>
{% csrf_token %}
{{ form.as_p }}
<button name='submit'>add entry</button>
</form>
{% endblock content %}
</body>
</html>

templates/lab_7/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "lab_7/base.html" %}
{% load bootstrap3 %}
{% block header %}
<h2>Add a new topic:</h2>
{% endblock header %}
{% block content %}
<form action="{% url 'lab_7:new_topic' %}" method='post' class="form">
{% csrf_token %}
{% bootstrap_form form %}
{% buttons %}
<button name="submit" class="btn btn-primary">add topic</button>
{% endbuttons %}
</form>
{% endblock content %}

</body>
</html>

templates/lab_7/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'lab_7/base.html' %}
{% block header %}
<h2>{{ topic }}</h2>
{% endblock header %}
{% block content %}
 <p>Topic: {{ topic }}</p>
<p>Entries:</p>
    <p>
<a href="{% url 'lab_7:new_entry' topic.id %}">add new entry</a>
</p>
	 <ul>
	 {% for entry in entries %}
<div class="panel panel-default">
<div class="panel-heading">
<h3>
{{ entry.date_added|date:'M d, Y H:i' }}
<small>
<a href="{% url 'lab_7:edit_entry' entry.id %}">
edit entry</a>
         </small>
</h3>
</div>
<div class="panel-body">
{{ entry.text|linebreaks }}
</div>
</div> <!-- panel -->
	 {% empty %}
There are no entries for this topic yet.
{% endfor %}
</ul>
{% endblock content %}
</body>
</html>

templates/lab_7/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "lab_7/base.html" %}
{% block header %}
<h1>Topics</h1>
{% endblock header %}
{% block content %}
<p>Topics</p>
<ul>
{% for topic in topics %}
<li>
<h3>
<a href="{% url 'lab_7:topic' topic.id %}">{{ topic }}</a>
</h3>
</li>
{% empty %}
<li>No topics have been added yet.</li>
{% endfor %}
</ul>
<h3><a href="{% url 'lab_7:new_topic' %}">Add new topic</h3>

{% endblock content %}
</body>
</html>

templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "lab_7/base.html" %}
{% load bootstrap3 %}
{% block header %}
<h2>Log in to your account.</h2>
{% endblock header %}
{% block content %}
    <form method="post" action="{% url 'users:login' %}" class="form">
{% csrf_token %}
{% bootstrap_form form %}
{% buttons %}
<button name="submit" class="btn btn-primary">log in</button>
{% endbuttons %}
<input type="hidden" name="next" value="{% url 'lab_7:index' %}" />
</form>
{% endblock content %}
</body>
</html>

templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "lab_7/base.html" %}
{% block content %}
<form method="post" action="{% url 'users:register' %}">
{% csrf_token %}
{{ form.as_p }}
<button name="submit">register</button>
    <input type="hidden" name="next" value="{% url 'lab_7:index' %}" />
</form>
{% endblock content %}

</body>
</html>